
name: hkmcmd-env

channels:
  - conda-forge

dependencies:

  # Core interpreter
  - python=3.10

  # Developer tools
  - pip
  - jupyter
  - pytest
  - black
  - mypy

  # Install your package + deps from pyproject.toml
  - pip:
      - -e .
